(setenv "PYMACS_PYTHON" "python2")
(el-get-envpath-prepend "PYTHONPATH" (expand-file-name "~/.emacs.d/el-get/pymacs2/"))
(el-get-envpath-prepend "PYTHONPATH" (expand-file-name "~/.emacs.d/el-get/rope/"))
(el-get-envpath-prepend "PYTHONPATH" (expand-file-name "~/.emacs.d/el-get/ropemode/"))
(el-get-envpath-prepend "PYTHONPATH" (expand-file-name "~/.emacs.d/el-get/ropemacs/"))
