(add-to-list 'load-path "~/.emacs.d/vendor/cedet/ede")
(add-to-list 'load-path "~/.emacs.d/vendor/cedet/eieio")
(add-to-list 'load-path "~/.emacs.d/vendor/cedet/semantic")
(add-to-list 'load-path "~/.emacs.d/vendor/cedet/speedbar")
(add-to-list 'load-path "~/.emacs.d/vendor/cedet/srecode")
(load-file "~/.emacs.d/vendor/cedet/common/cedet.el")
(require 'semantic-ia)
(setq semanticdb-default-save-directory "~/.emacs.d/emacs-meta/semantic.cache/")
(semantic-load-enable-excessive-code-helpers)
(global-semantic-stickyfunc-mode -1)
(global-semantic-decoration-mode -1)
(global-senator-minor-mode -1)
